minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@types/node"
overrides:
  brace-expansion@>=1.0.0 <=1.1.11: ">=1.1.12"
  brace-expansion@>=2.0.0 <=2.0.1: ">=2.0.2"
  form-data@>=4.0.0 <4.0.4: ">=4.0.4"
  tmp@<=0.2.3: ">=0.2.4"
  vite@>=6.0.0 <=6.3.5: ">=6.3.6"
